//deploy/make-config.js -- generates rss.chat's config.json on stdout from env vars.
//Part of the deploy overlay, not upstream code.

function required (name) {
	const theValue = process.env [name];
	if ((theValue === undefined) || (theValue.length === 0)) {
		console.error ("make-config: " + name + " is required");
		process.exit (1);
		}
	return (theValue);
	}
function optional (name, theDefault) {
	const theValue = process.env [name];
	if ((theValue === undefined) || (theValue.length === 0)) {
		return (theDefault);
		}
	return (theValue);
	}

const domain = required ("RSSCHAT_DOMAIN");
const productName = optional ("PRODUCT_NAME", "rss.chat");

const config = {
	note: "Generated by deploy/make-config.js at container start. Do not edit; set env vars in deploy/.env instead.",
	port: 1452,
	flWebsocketEnabled: true,
	websocketPort: 1462,
	flSecureWebsocket: true, //TLS terminates at caddy; the client connects wss://
	urlWebsocketServerForClient: "wss://" + domain + "/",

	productName: productName,
	productNameForDisplay: productName,
	myDomain: domain,
	urlServerForClient: "https://" + domain + "/",
	urlServerForEmail: "https://" + domain + "/",
	pathServerHomePageSource: optional ("HOMEPAGE_PATH", "/app/static-src/client/index.html"),

	prefsPath: "data/prefs.json", //on the rsschat-data volume
	dataPath: "data/",

	mailSender: optional ("MAIL_SENDER", "rsschat@localhost"),
	confirmEmailSubject: productName + " confirmation",
	operationToConfirm: "sign in to " + productName,
	smtpHost: optional ("SMTP_HOST", "mailpit"),
	smtpPort: Number (optional ("SMTP_PORT", "1025")),
	smtpUsername: optional ("SMTP_USERNAME", ""),
	smtpPassword: optional ("SMTP_PASSWORD", ""),

	//feeds live in the database and the server serves them itself, at /users/<name>/rss.xml
	//and /data/subs.opml -- no Amazon, no S3 credentials. rssFeedUrl and opmlListUrl are
	//derived from urlServerForClient by the server (rssnetwork.js initDatabaseUrls), so the
	//four S3 location settings are deliberately absent.
	flFeedsInDatabase: true,
	rssFilename: "rss.xml",
	flRssCloudEnabled: optional ("RSSCLOUD_ENABLED", "true") === "true",

	database: {
		host: optional ("MYSQL_HOST", "mysql"),
		port: 3306,
		user: optional ("MYSQL_USER", "rsschat"),
		password: required ("MYSQL_PASSWORD"),
		charset: "utf8mb4",
		connectionLimit: 100,
		database: optional ("MYSQL_DATABASE", "rsschat"),
		debug: false,
		flUseMySql2: true
		}
	};

const whitelist = optional ("WHITELIST", "");
const whitelistArray = whitelist.split (",").map (function (s) {
	return (s.trim ());
	}).filter (function (s) {
	return (s.length > 0);
	});
if (whitelistArray.length > 0) {
	config.whitelist = whitelistArray;
	}

console.log (JSON.stringify (config, undefined, "\t"));
